eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-feign
  resources:
      static-locations: classpath:/templates/webpage/views/
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 10240Mb
      max-request-size: 102400Mb
feign:
  hystrix:
    enabled: true


