eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-feign
  resources:
      static-locations: classpath:/templates
  servlet:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 10240Mb
feign:
  hystrix:
    enabled: true


