eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-feign
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
feign:
  hystrix:
    enabled: true

