server:
  port: 8762
  # 数据库基本配置
spring:
  application:
    name: eureka-client
  datasource:
      url: jdbc:mysql://172.16.107.206:3306/demo
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 10240Mb
  # 显示后台处理的SQL语句
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


